### ISSUE TITLE
Investigate the concurrency issue which breaks the REST tests randomly

### ISSUE THREAD

**Issue by arnodb** [arnodb/dspace-rest-client#3]
```
2015-10-21 21:04:57,219 ERROR org.dspace.storage.rdbms.DatabaseManager @ SQL QueryTable Error - 
org.postgresql.util.PSQLException: Ce statement a été fermé.
        at org.postgresql.jdbc2.AbstractJdbc2Statement.checkClosed(AbstractJdbc2Statement.java:2635)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.setInt(AbstractJdbc2Statement.java:1276)
        at org.apache.commons.dbcp.DelegatingPreparedStatement.setInt(DelegatingPreparedStatement.java:120)
        at org.apache.commons.dbcp.DelegatingPreparedStatement.setInt(DelegatingPreparedStatement.java:120)
        at org.apache.commons.dbcp.DelegatingPreparedStatement.setInt(DelegatingPreparedStatement.java:120)
        at org.dspace.storage.rdbms.DatabaseManager.loadParameters(DatabaseManager.java:1545)
        at org.dspace.storage.rdbms.DatabaseManager.queryTable(DatabaseManager.java:232)
        at org.dspace.storage.rdbms.DatabaseManager.querySingleTable(DatabaseManager.java:381)
        at org.dspace.storage.rdbms.DatabaseManager.findByUnique(DatabaseManager.java:546)
        at org.dspace.storage.rdbms.DatabaseManager.find(DatabaseManager.java:505)
        at org.dspace.content.Community.find(Community.java:131)
        at org.dspace.rest.CommunitiesResource.findCommunity(CommunitiesResource.java:1063)
        at org.dspace.rest.CommunitiesResource.deleteCommunity(CommunitiesResource.java:794)
```

**Comment by arnodb** [comment]
Solved by various fixes in DSpace REST API.
